; generated by PrusaSlicer 2.9.2 on 2025-11-02 at 22:51:31 UTC

; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M201 X500 Y500 Z100 E5000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z10 E60 ; sets maximum feedrates, mm / sec
M204 S500 T1000 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E5.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

; printing object square.stl id:0 copy 0
; stop printing object square.stl id:0 copy 0

;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S150 ; set temporary nozzle temp to prevent oozing during homing
M140 S60 ; set final bed temp
G4 S30 ; allow partial nozzle warmup
G28 ; home all axis and restore leveling
G1 Z50 F240
G1 X2.0 Y10 F3000
M104 S210 ; set final nozzle temp
M190 S60 ; wait for bed temp to stabilize
M109 S210 ; wait for nozzle temp to stabilize
G1 Z0.28 F240
G92 E0
G1 X2.0 Y140 E10 F1500 ; prime the nozzle
G1 X2.3 Y140 F5000
G92 E0
G1 X2.3 Y10 E10 F1200 ; prime the nozzle
G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-.8 F1800
G1 Z.2 F9000
G1 X128.289 Y127.309
G1 Z.2
G1 E.8 F1800
M204 S500
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1108
G1 X130 Y126.811 E.05587
G1 X170 Y126.811 E1.25417
G1 X171.535 Y127.205 E.04969
G1 X172.691 Y128.289 E.04969
G1 X173.189 Y130 E.05587
G1 X173.189 Y170 E1.25417
G1 X172.795 Y171.535 E.04969
G1 X171.711 Y172.691 E.04969
G1 X170 Y173.189 E.05587
G1 X130 Y173.189 E1.25417
G1 X128.465 Y172.795 E.04969
G1 X127.309 Y171.711 E.04969
G1 X126.811 Y170 E.05587
G1 X126.811 Y130 E1.25417
G1 X127.205 Y128.465 E.04969
G1 X128.248 Y127.353 E.0478
;WIPE_START
G1 F7200
G1 X128.289 Y127.309 E-.01428
G1 X130 Y126.811 E-.42323
G1 X131.526 Y126.811 E-.36249
;WIPE_END
; printing object square.stl id:0 copy 0
G1 X130.289 Y130.289 F9000
G1 E.8 F1800
;TYPE:External perimeter
;WIDTH:0.578422
G1 F1108
G1 X130.384 Y130.27 E.00431
;WIDTH:0.539211
G1 X130.479 Y130.25 E.00401
;WIDTH:0.5
G1 X169.521 Y130.25 E1.48384
;WIDTH:0.539211
G1 X169.616 Y130.27 E.00401
;WIDTH:0.578422
G1 X169.711 Y130.289 E.00431
G1 X169.73 Y130.384 E.00431
;WIDTH:0.539211
G1 X169.75 Y130.479 E.00401
;WIDTH:0.5
G1 X169.75 Y169.521 E1.48384
;WIDTH:0.539211
G1 X169.73 Y169.616 E.00401
;WIDTH:0.578422
G1 X169.711 Y169.711 E.00431
G1 X169.616 Y169.73 E.00431
;WIDTH:0.539211
G1 X169.521 Y169.75 E.00401
;WIDTH:0.5
G1 X130.479 Y169.75 E1.48384
;WIDTH:0.539211
G1 X130.384 Y169.73 E.00401
;WIDTH:0.578422
G1 X130.289 Y169.711 E.00431
G1 X130.27 Y169.616 E.00431
;WIDTH:0.539211
G1 X130.25 Y169.521 E.00401
;WIDTH:0.5
G1 X130.25 Y130.479 E1.48384
;WIDTH:0.539211
G1 X130.27 Y130.384 E.00401
;WIDTH:0.578422
G1 X130.277 Y130.348 E.00163
M106 S255
;LAYER_CHANGE
;Z:0.44
;HEIGHT:0.24
;BEFORE_LAYER_CHANGE
G92 E0
;0.44


;WIPE_START
G1 F7200
G1 X130.289 Y130.289 E-.0143
G1 X130.384 Y130.27 E-.02301
G1 X130.479 Y130.25 E-.02306
G1 X133.593 Y130.25 E-.73963
;WIPE_END
G1 Z.44 F9000
;AFTER_LAYER_CHANGE
;0.44
M104 S205 ; set temperature
; stop printing object square.stl id:0 copy 0
G1 Z.44
G1 X126.942 Y129.492
G1 E.8 F1800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1047
G1 X127.205 Y128.465 E.03898
G1 X128.289 Y127.309 E.05827
G1 X130 Y126.811 E.06552
G1 X170 Y126.811 E1.47075
G1 X171.535 Y127.205 E.05827
G1 X172.691 Y128.289 E.05827
G1 X173.189 Y130 E.06552
G1 X173.189 Y170 E1.47075
G1 X172.795 Y171.535 E.05827
G1 X171.711 Y172.691 E.05827
G1 X170 Y173.189 E.06552
G1 X130 Y173.189 E1.47075
G1 X128.465 Y172.795 E.05827
G1 X127.309 Y171.711 E.05827
G1 X126.811 Y170 E.06552
G1 X126.811 Y130 E1.47075
G1 X126.927 Y129.55 E.01709
;WIPE_START
G1 F7200
G1 X126.942 Y129.492 E-.01423
G1 X127.205 Y128.465 E-.25178
G1 X128.289 Y127.309 E-.37638
G1 X128.926 Y127.124 E-.15761
;WIPE_END
; printing object square.stl id:0 copy 0
G1 X130.288 Y130.288 F9000
G1 E.8 F1800
;TYPE:External perimeter
;WIDTH:0.576948
G1 F1047
G1 X130.381 Y130.269 E.00498
;WIDTH:0.538474
G1 X130.474 Y130.25 E.00461
;WIDTH:0.5
G1 X169.526 Y130.25 E1.74762
;WIDTH:0.538475
G1 X169.619 Y130.269 E.00461
;WIDTH:0.57695
G1 X169.712 Y130.288 E.00498
G1 X169.731 Y130.381 E.00498
;WIDTH:0.538475
G1 X169.75 Y130.474 E.00461
;WIDTH:0.5
G1 X169.75 Y169.526 E1.74762
;WIDTH:0.538475
G1 X169.731 Y169.619 E.00461
;WIDTH:0.57695
G1 X169.712 Y169.712 E.00498
G1 X169.619 Y169.731 E.00498
;WIDTH:0.538475
G1 X169.526 Y169.75 E.00461
;WIDTH:0.5
G1 X130.474 Y169.75 E1.74762
;WIDTH:0.538474
G1 X130.381 Y169.731 E.00461
;WIDTH:0.576948
G1 X130.288 Y169.712 E.00498
G1 X130.269 Y169.619 E.00498
;WIDTH:0.538474
G1 X130.25 Y169.526 E.00461
;WIDTH:0.5
G1 X130.25 Y130.474 E1.74762
;WIDTH:0.538474
G1 X130.269 Y130.381 E.00461
;WIDTH:0.576948
G1 X130.276 Y130.347 E.00182
;LAYER_CHANGE
;Z:0.68
;HEIGHT:0.24
;BEFORE_LAYER_CHANGE
G92 E0
;0.68


;WIPE_START
G1 F7200
G1 X130.288 Y130.288 E-.0143
G1 X130.381 Y130.269 E-.02254
G1 X130.474 Y130.25 E-.02254
G1 X133.592 Y130.25 E-.74062
;WIPE_END
G1 Z.68 F9000
;AFTER_LAYER_CHANGE
;0.68
G1 Z.68
G1 X130.288 Y130.288
G1 E.8 F1800
G1 F900
G1 X130.381 Y130.269 E.00498
;WIDTH:0.538474
G1 X130.474 Y130.25 E.00461
;WIDTH:0.5
G1 X169.526 Y130.25 E1.74762
;WIDTH:0.538475
G1 X169.619 Y130.269 E.00461
;WIDTH:0.57695
G1 X169.712 Y130.288 E.00498
G1 X169.731 Y130.381 E.00498
;WIDTH:0.538475
G1 X169.75 Y130.474 E.00461
;WIDTH:0.5
G1 X169.75 Y169.526 E1.74762
;WIDTH:0.538475
G1 X169.731 Y169.619 E.00461
;WIDTH:0.57695
G1 X169.712 Y169.712 E.00498
G1 X169.619 Y169.731 E.00498
;WIDTH:0.538475
G1 X169.526 Y169.75 E.00461
;WIDTH:0.5
G1 X130.474 Y169.75 E1.74762
;WIDTH:0.538474
G1 X130.381 Y169.731 E.00461
;WIDTH:0.576948
G1 X130.288 Y169.712 E.00498
G1 X130.269 Y169.619 E.00498
;WIDTH:0.538474
G1 X130.25 Y169.526 E.00461
;WIDTH:0.5
G1 X130.25 Y130.474 E1.74762
;WIDTH:0.538474
G1 X130.269 Y130.381 E.00461
;WIDTH:0.576948
G1 X130.276 Y130.347 E.00182
;LAYER_CHANGE
;Z:0.92
;HEIGHT:0.24
;BEFORE_LAYER_CHANGE
G92 E0
;0.92


;WIPE_START
G1 F7200
G1 X130.288 Y130.288 E-.0143
G1 X130.381 Y130.269 E-.02254
G1 X130.474 Y130.25 E-.02254
G1 X133.592 Y130.25 E-.74062
;WIPE_END
G1 Z.92 F9000
;AFTER_LAYER_CHANGE
;0.92
G1 Z.92
G1 X130.288 Y130.288
G1 E.8 F1800
G1 F900
G1 X130.381 Y130.269 E.00498
;WIDTH:0.538474
G1 X130.474 Y130.25 E.00461
;WIDTH:0.5
G1 X169.526 Y130.25 E1.74762
;WIDTH:0.538475
G1 X169.619 Y130.269 E.00461
;WIDTH:0.57695
G1 X169.712 Y130.288 E.00498
G1 X169.731 Y130.381 E.00498
;WIDTH:0.538475
G1 X169.75 Y130.474 E.00461
;WIDTH:0.5
G1 X169.75 Y169.526 E1.74762
;WIDTH:0.538475
G1 X169.731 Y169.619 E.00461
;WIDTH:0.57695
G1 X169.712 Y169.712 E.00498
G1 X169.619 Y169.731 E.00498
;WIDTH:0.538475
G1 X169.526 Y169.75 E.00461
;WIDTH:0.5
G1 X130.474 Y169.75 E1.74762
;WIDTH:0.538474
G1 X130.381 Y169.731 E.00461
;WIDTH:0.576948
G1 X130.288 Y169.712 E.00498
G1 X130.269 Y169.619 E.00498
;WIDTH:0.538474
G1 X130.25 Y169.526 E.00461
;WIDTH:0.5
G1 X130.25 Y130.474 E1.74762
;WIDTH:0.538474
G1 X130.269 Y130.381 E.00461
;WIDTH:0.576948
G1 X130.276 Y130.347 E.00182
;LAYER_CHANGE
;Z:1.16
;HEIGHT:0.24
;BEFORE_LAYER_CHANGE
G92 E0
;1.16


;WIPE_START
G1 F7200
G1 X130.288 Y130.288 E-.0143
G1 X130.381 Y130.269 E-.02254
G1 X130.474 Y130.25 E-.02254
G1 X133.592 Y130.25 E-.74062
;WIPE_END
G1 Z1.16 F9000
;AFTER_LAYER_CHANGE
;1.16
G1 Z1.16
G1 X130.288 Y130.288
G1 E.8 F1800
G1 F900
G1 X130.381 Y130.269 E.00498
;WIDTH:0.538474
G1 X130.474 Y130.25 E.00461
;WIDTH:0.5
G1 X169.526 Y130.25 E1.74762
;WIDTH:0.538475
G1 X169.619 Y130.269 E.00461
;WIDTH:0.57695
G1 X169.712 Y130.288 E.00498
G1 X169.731 Y130.381 E.00498
;WIDTH:0.538475
G1 X169.75 Y130.474 E.00461
;WIDTH:0.5
G1 X169.75 Y169.526 E1.74762
;WIDTH:0.538475
G1 X169.731 Y169.619 E.00461
;WIDTH:0.57695
G1 X169.712 Y169.712 E.00498
G1 X169.619 Y169.731 E.00498
;WIDTH:0.538475
G1 X169.526 Y169.75 E.00461
;WIDTH:0.5
G1 X130.474 Y169.75 E1.74762
;WIDTH:0.538474
G1 X130.381 Y169.731 E.00461
;WIDTH:0.576948
G1 X130.288 Y169.712 E.00498
G1 X130.269 Y169.619 E.00498
;WIDTH:0.538474
G1 X130.25 Y169.526 E.00461
;WIDTH:0.5
G1 X130.25 Y130.474 E1.74762
;WIDTH:0.538474
G1 X130.269 Y130.381 E.00461
;WIDTH:0.576948
G1 X130.276 Y130.347 E.00182
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.24
;BEFORE_LAYER_CHANGE
G92 E0
;1.4


;WIPE_START
G1 F7200
G1 X130.288 Y130.288 E-.0143
G1 X130.381 Y130.269 E-.02254
G1 X130.474 Y130.25 E-.02254
G1 X133.592 Y130.25 E-.74062
;WIPE_END
G1 Z1.4 F9000
;AFTER_LAYER_CHANGE
;1.4
G1 Z1.4
G1 X130.288 Y130.288
G1 E.8 F1800
G1 F900
G1 X130.381 Y130.269 E.00498
;WIDTH:0.538474
G1 X130.474 Y130.25 E.00461
;WIDTH:0.5
G1 X169.526 Y130.25 E1.74762
;WIDTH:0.538475
G1 X169.619 Y130.269 E.00461
;WIDTH:0.57695
G1 X169.712 Y130.288 E.00498
G1 X169.731 Y130.381 E.00498
;WIDTH:0.538475
G1 X169.75 Y130.474 E.00461
;WIDTH:0.5
G1 X169.75 Y169.526 E1.74762
;WIDTH:0.538475
G1 X169.731 Y169.619 E.00461
;WIDTH:0.57695
G1 X169.712 Y169.712 E.00498
G1 X169.619 Y169.731 E.00498
;WIDTH:0.538475
G1 X169.526 Y169.75 E.00461
;WIDTH:0.5
G1 X130.474 Y169.75 E1.74762
;WIDTH:0.538474
G1 X130.381 Y169.731 E.00461
;WIDTH:0.576948
G1 X130.288 Y169.712 E.00498
G1 X130.269 Y169.619 E.00498
;WIDTH:0.538474
G1 X130.25 Y169.526 E.00461
;WIDTH:0.5
G1 X130.25 Y130.474 E1.74762
;WIDTH:0.538474
G1 X130.269 Y130.381 E.00461
;WIDTH:0.576948
G1 X130.276 Y130.347 E.00182
;LAYER_CHANGE
;Z:1.64
;HEIGHT:0.24
;BEFORE_LAYER_CHANGE
G92 E0
;1.64


;WIPE_START
G1 F7200
G1 X130.288 Y130.288 E-.0143
G1 X130.381 Y130.269 E-.02254
G1 X130.474 Y130.25 E-.02254
G1 X133.592 Y130.25 E-.74062
;WIPE_END
G1 Z1.64 F9000
;AFTER_LAYER_CHANGE
;1.64
G1 Z1.64
G1 X130.977 Y130.977
G1 E.8 F1800
;TYPE:Perimeter
;WIDTH:0.439999
G1 F3600
G1 X169.023 Y130.977 E1.47482
G1 X169.023 Y150 E.73741
G1 X169.023 Y169.023 E.73741
G1 X130.977 Y169.023 E1.47482
G1 X130.977 Y131.037 E1.4725
G1 X130.588 Y130.588 F9000
G1 F3600
G1 X169.412 Y130.588 E1.50498
G1 X169.412 Y150 E.75249
G1 X169.412 Y169.412 E.75249
G1 X130.588 Y169.412 E1.50498
G1 X130.588 Y130.648 E1.50265
G1 X130.21 Y130.21 F9000
;TYPE:External perimeter
;WIDTH:0.419999
G1 F1800
G1 X169.79 Y130.21 E1.4553
G1 X169.79 Y150 E.72765
G1 X169.79 Y169.79 E.72765
G1 X130.21 Y169.79 E1.4553
G1 X130.21 Y130.27 E1.45309
;WIPE_START
G1 F7200
G1 X130.21 Y130.21 E-.01425
G1 X133.518 Y130.21 E-.78575
;WIPE_END
G1 X131.302 Y131.104 F9000
G1 E.8 F1800
M204 S250
;TYPE:Bridge infill
;WIDTH:0.389956
;HEIGHT:0.389872
G1 F1500
G1 X131.302 Y168.698 E1.8667
G1 X131.742 Y168.698 E.02185
G1 X131.742 Y131.302 E1.85686
G1 X132.182 Y131.302 E.02185
G1 X132.182 Y168.698 E1.85686
G1 X132.622 Y168.698 E.02185
G1 X132.622 Y131.302 E1.85686
G1 X133.062 Y131.302 E.02185
G1 X133.062 Y168.698 E1.85686
G1 X133.502 Y168.698 E.02185
G1 X133.502 Y131.302 E1.85686
G1 X133.942 Y131.302 E.02185
G1 X133.942 Y168.698 E1.85686
G1 X134.382 Y168.698 E.02185
G1 X134.382 Y131.302 E1.85686
G1 X134.822 Y131.302 E.02185
G1 X134.822 Y168.698 E1.85686
G1 X135.262 Y168.698 E.02185
G1 X135.262 Y131.302 E1.85686
G1 X135.701 Y131.302 E.0218
G1 X135.701 Y168.698 E1.85686
G1 X136.141 Y168.698 E.02185
G1 X136.141 Y131.302 E1.85686
G1 X136.581 Y131.302 E.02185
G1 X136.581 Y168.698 E1.85686
G1 X137.021 Y168.698 E.02185
G1 X137.021 Y131.302 E1.85686
G1 X137.461 Y131.302 E.02185
G1 X137.461 Y168.698 E1.85686
G1 X137.901 Y168.698 E.02185
G1 X137.901 Y131.302 E1.85686
G1 X138.341 Y131.302 E.02185
G1 X138.341 Y168.698 E1.85686
G1 X138.781 Y168.698 E.02185
G1 X138.781 Y131.302 E1.85686
G1 X139.221 Y131.302 E.02185
G1 X139.221 Y168.698 E1.85686
G1 X139.661 Y168.698 E.02185
G1 X139.661 Y131.302 E1.85686
G1 X140.101 Y131.302 E.02185
G1 X140.101 Y168.698 E1.85686
G1 X140.541 Y168.698 E.02185
G1 X140.541 Y131.302 E1.85686
G1 X140.981 Y131.302 E.02185
G1 X140.981 Y168.698 E1.85686
G1 X141.421 Y168.698 E.02185
G1 X141.421 Y131.302 E1.85686
G1 X141.861 Y131.302 E.02185
G1 X141.861 Y168.698 E1.85686
G1 X142.301 Y168.698 E.02185
G1 X142.301 Y131.302 E1.85686
G1 X142.741 Y131.302 E.02185
G1 X142.741 Y168.698 E1.85686
G1 X143.181 Y168.698 E.02185
G1 X143.181 Y131.302 E1.85686
G1 X143.621 Y131.302 E.02185
G1 X143.621 Y168.698 E1.85686
G1 X144.061 Y168.698 E.02185
G1 X144.061 Y131.302 E1.85686
G1 X144.501 Y131.302 E.02185
G1 X144.501 Y168.698 E1.85686
G1 X144.941 Y168.698 E.02185
G1 X144.941 Y131.302 E1.85686
G1 X145.381 Y131.302 E.02185
G1 X145.38 Y168.698 E1.85686
G1 X145.82 Y168.698 E.02185
G1 X145.82 Y131.302 E1.85686
G1 X146.26 Y131.302 E.02185
G1 X146.26 Y168.698 E1.85686
G1 X146.7 Y168.698 E.02185
G1 X146.7 Y131.302 E1.85686
G1 X147.14 Y131.302 E.02185
G1 X147.14 Y168.698 E1.85686
G1 X147.58 Y168.698 E.02185
G1 X147.58 Y131.302 E1.85686
G1 X148.02 Y131.302 E.02185
G1 X148.02 Y168.698 E1.85686
G1 X148.46 Y168.698 E.02185
G1 X148.46 Y131.302 E1.85686
G1 X148.9 Y131.302 E.02185
G1 X148.9 Y168.698 E1.85686
G1 X149.34 Y168.698 E.02185
G1 X149.34 Y131.302 E1.85686
G1 X149.78 Y131.302 E.02185
G1 X149.78 Y168.698 E1.85686
G1 X150.22 Y168.698 E.02185
G1 X150.22 Y131.302 E1.85686
G1 X150.66 Y131.302 E.02185
G1 X150.66 Y168.698 E1.85686
G1 X151.1 Y168.698 E.02185
G1 X151.1 Y131.302 E1.85686
G1 X151.54 Y131.302 E.02185
G1 X151.54 Y168.698 E1.85686
G1 X151.98 Y168.698 E.02185
G1 X151.98 Y131.302 E1.85686
G1 X152.42 Y131.302 E.02185
G1 X152.42 Y168.698 E1.85686
G1 X152.86 Y168.698 E.02185
G1 X152.86 Y131.302 E1.85686
G1 X153.3 Y131.302 E.02185
G1 X153.3 Y168.698 E1.85686
G1 X153.74 Y168.698 E.02185
G1 X153.74 Y131.302 E1.85686
G1 X154.18 Y131.302 E.02185
G1 X154.18 Y168.698 E1.85686
G1 X154.62 Y168.698 E.02185
G1 X154.62 Y131.302 E1.85686
G1 X155.06 Y131.302 E.02185
G1 X155.06 Y168.698 E1.85686
G1 X155.499 Y168.698 E.0218
G1 X155.499 Y131.302 E1.85686
G1 X155.939 Y131.302 E.02185
G1 X155.939 Y168.698 E1.85686
G1 X156.379 Y168.698 E.02185
G1 X156.379 Y131.302 E1.85686
G1 X156.819 Y131.302 E.02185
G1 X156.819 Y168.698 E1.85686
G1 X157.259 Y168.698 E.02185
G1 X157.259 Y131.302 E1.85686
G1 X157.699 Y131.302 E.02185
G1 X157.699 Y168.698 E1.85686
G1 X158.139 Y168.698 E.02185
G1 X158.139 Y131.302 E1.85686
G1 X158.579 Y131.302 E.02185
G1 X158.579 Y168.698 E1.85686
G1 X159.019 Y168.698 E.02185
G1 X159.019 Y131.302 E1.85686
G1 X159.459 Y131.302 E.02185
G1 X159.459 Y168.698 E1.85686
G1 X159.899 Y168.698 E.02185
G1 X159.899 Y131.302 E1.85686
G1 X160.339 Y131.302 E.02185
G1 X160.339 Y168.698 E1.85686
G1 X160.779 Y168.698 E.02185
G1 X160.779 Y131.302 E1.85686
G1 X161.219 Y131.302 E.02185
G1 X161.219 Y168.698 E1.85686
G1 X161.659 Y168.698 E.02185
G1 X161.659 Y131.302 E1.85686
G1 X162.099 Y131.302 E.02185
G1 X162.099 Y168.698 E1.85686
G1 X162.539 Y168.698 E.02185
G1 X162.539 Y131.302 E1.85686
G1 X162.979 Y131.302 E.02185
G1 X162.979 Y168.698 E1.85686
G1 X163.419 Y168.698 E.02185
G1 X163.419 Y131.302 E1.85686
G1 X163.859 Y131.302 E.02185
G1 X163.859 Y168.698 E1.85686
G1 X164.299 Y168.698 E.02185
G1 X164.299 Y131.302 E1.85686
G1 X164.739 Y131.302 E.02185
G1 X164.739 Y168.698 E1.85686
G1 X165.179 Y168.698 E.02185
G1 X165.179 Y131.302 E1.85686
G1 X165.618 Y131.302 E.0218
G1 X165.618 Y168.698 E1.85686
G1 X166.058 Y168.698 E.02185
G1 X166.058 Y131.302 E1.85686
G1 X166.498 Y131.302 E.02185
G1 X166.498 Y168.698 E1.85686
G1 X166.938 Y168.698 E.02185
G1 X166.938 Y131.302 E1.85686
G1 X167.378 Y131.302 E.02185
G1 X167.378 Y168.698 E1.85686
G1 X167.818 Y168.698 E.02185
G1 X167.818 Y131.302 E1.85686
G1 X168.258 Y131.302 E.02185
G1 X168.258 Y168.698 E1.85686
G1 X168.698 Y168.698 E.02185
G1 X168.698 Y131.104 E1.8667
M204 S500
;LAYER_CHANGE
;Z:1.88
;HEIGHT:0.24
;BEFORE_LAYER_CHANGE
G92 E0
;1.88


;WIPE_START
G1 F7200
G1 X168.698 Y134.472 E-.8
;WIPE_END
G1 Z1.88 F9000
;AFTER_LAYER_CHANGE
;1.88
G1 Z1.88
G1 X169.023 Y130.977
G1 E.8 F1800
;TYPE:Perimeter
;WIDTH:0.439999
G1 F3600
G1 X169.023 Y150 E.73741
G1 X169.023 Y169.023 E.73741
G1 X130.977 Y169.023 E1.47482
G1 X130.977 Y130.977 E1.47482
G1 X168.963 Y130.977 E1.4725
G1 X169.412 Y130.588 F9000
G1 F3600
G1 X169.412 Y150 E.75249
G1 X169.412 Y169.412 E.75249
G1 X130.588 Y169.412 E1.50498
G1 X130.588 Y130.588 E1.50498
G1 X169.352 Y130.588 E1.50265
G1 X169.79 Y130.21 F9000
;TYPE:External perimeter
;WIDTH:0.419999
G1 F1800
G1 X169.79 Y150 E.72765
G1 X169.79 Y169.79 E.72765
G1 X130.21 Y169.79 E1.4553
G1 X130.21 Y130.21 E1.4553
G1 X169.73 Y130.21 E1.45309
;WIPE_START
G1 F7200
G1 X169.79 Y130.21 E-.01425
G1 X169.79 Y133.518 E-.78575
;WIPE_END
G1 X168.194 Y168.901 F9000
G1 E.8 F1800
;TYPE:Top solid infill
;WIDTH:0.401232
G1 X168.744 Y168.35 E.02717
G1 X168.744 Y167.856 E.01724
G1 X167.856 Y168.744 E.04382
G1 X167.361 Y168.744 E.01727
G1 X168.744 Y167.361 E.06825
G1 X168.744 Y166.867 E.01724
G1 X166.867 Y168.744 E.09263
G1 X166.372 Y168.744 E.01727
G1 X168.744 Y166.372 E.11706
G1 X168.744 Y165.877 E.01727
G1 X165.877 Y168.744 E.14149
G1 X165.383 Y168.744 E.01724
G1 X168.744 Y165.383 E.16587
G1 X168.744 Y164.888 E.01727
G1 X164.888 Y168.744 E.1903
G1 X164.394 Y168.744 E.01724
G1 X168.744 Y164.394 E.21467
G1 X168.744 Y163.899 E.01727
G1 X163.899 Y168.744 E.2391
G1 X163.405 Y168.744 E.01724
G1 X168.744 Y163.405 E.26348
G1 X168.744 Y162.91 E.01727
G1 X162.91 Y168.744 E.28791
G1 X162.415 Y168.744 E.01727
G1 X168.744 Y162.415 E.31234
G1 X168.744 Y161.921 E.01724
G1 X161.921 Y168.744 E.33672
G1 X161.426 Y168.744 E.01727
G1 X168.744 Y161.426 E.36115
G1 X168.744 Y160.932 E.01724
G1 X160.932 Y168.744 E.38553
G1 X160.437 Y168.744 E.01727
G1 X168.744 Y160.437 E.40995
G1 X168.744 Y159.942 E.01727
G1 X159.942 Y168.744 E.43438
G1 X159.448 Y168.744 E.01724
G1 X168.744 Y159.448 E.45876
G1 X168.744 Y158.953 E.01727
G1 X158.953 Y168.744 E.48319
G1 X158.459 Y168.744 E.01724
G1 X168.744 Y158.459 E.50757
G1 X168.744 Y157.964 E.01727
G1 X157.964 Y168.744 E.532
G1 X157.469 Y168.744 E.01727
G1 X168.744 Y157.469 E.55643
G1 X168.744 Y156.975 E.01724
G1 X156.975 Y168.744 E.5808
G1 X156.48 Y168.744 E.01727
G1 X168.744 Y156.48 E.60523
G1 X168.744 Y155.986 E.01724
G1 X155.986 Y168.744 E.62961
G1 X155.491 Y168.744 E.01727
G1 X168.744 Y155.491 E.65404
G1 X168.744 Y154.996 E.01727
G1 X154.996 Y168.744 E.67847
G1 X154.502 Y168.744 E.01724
G1 X168.744 Y154.502 E.70285
G1 X168.744 Y154.007 E.01727
G1 X154.007 Y168.744 E.72728
G1 X153.513 Y168.744 E.01724
G1 X168.744 Y153.513 E.75166
G1 X168.744 Y153.018 E.01727
G1 X153.018 Y168.744 E.77608
G1 X152.524 Y168.744 E.01724
G1 X168.744 Y152.524 E.80046
G1 X168.744 Y152.029 E.01727
G1 X152.029 Y168.744 E.82489
G1 X151.534 Y168.744 E.01727
G1 X168.744 Y151.534 E.84932
G1 X168.744 Y151.04 E.01724
G1 X151.04 Y168.744 E.8737
G1 X150.545 Y168.744 E.01727
G1 X168.744 Y150.545 E.89813
G1 X168.744 Y150.051 E.01724
G1 X150.051 Y168.744 E.92251
G1 X149.556 Y168.744 E.01727
G1 X168.744 Y149.556 E.94694
G1 X168.744 Y149.061 E.01727
G1 X149.061 Y168.744 E.97136
G1 X148.567 Y168.744 E.01724
G1 X168.744 Y148.567 E.99574
G1 X168.744 Y148.072 E.01727
G1 X148.072 Y168.744 E1.02017
G1 X147.578 Y168.744 E.01724
G1 X168.744 Y147.578 E1.04455
G1 X168.744 Y147.083 E.01727
G1 X147.083 Y168.744 E1.06898
G1 X146.588 Y168.744 E.01727
G1 X168.744 Y146.588 E1.09341
G1 X168.744 Y146.094 E.01724
G1 X146.094 Y168.744 E1.11779
G1 X145.599 Y168.744 E.01727
G1 X168.744 Y145.599 E1.14221
G1 X168.744 Y145.105 E.01724
G1 X145.105 Y168.744 E1.16659
G1 X144.61 Y168.744 E.01727
G1 X168.744 Y144.61 E1.19102
G1 X168.744 Y144.116 E.01724
G1 X144.115 Y168.744 E1.21543
G1 X143.621 Y168.744 E.01724
G1 X168.744 Y143.621 E1.23983
G1 X168.744 Y143.126 E.01727
G1 X143.126 Y168.744 E1.26426
G1 X142.632 Y168.744 E.01724
G1 X168.744 Y142.632 E1.28864
G1 X168.744 Y142.137 E.01727
G1 X142.137 Y168.744 E1.31307
G1 X141.643 Y168.744 E.01724
G1 X168.744 Y141.643 E1.33745
G1 X168.744 Y141.148 E.01727
G1 X141.148 Y168.744 E1.36187
G1 X140.653 Y168.744 E.01727
G1 X168.744 Y140.653 E1.3863
G1 X168.744 Y140.159 E.01724
G1 X140.159 Y168.744 E1.41068
G1 X139.664 Y168.744 E.01727
G1 X168.744 Y139.664 E1.43511
G1 X168.744 Y139.17 E.01724
G1 X139.17 Y168.744 E1.45949
G1 X138.675 Y168.744 E.01727
G1 X168.744 Y138.675 E1.48392
G1 X168.744 Y138.18 E.01727
G1 X138.18 Y168.744 E1.50835
G1 X137.686 Y168.744 E.01724
G1 X168.744 Y137.686 E1.53272
G1 X168.744 Y137.191 E.01727
G1 X137.191 Y168.744 E1.55715
G1 X136.697 Y168.744 E.01724
G1 X168.744 Y136.697 E1.58153
G1 X168.744 Y136.202 E.01727
G1 X136.202 Y168.744 E1.60596
G1 X135.707 Y168.744 E.01727
G1 X168.744 Y135.707 E1.63039
G1 X168.744 Y135.213 E.01724
G1 X135.213 Y168.744 E1.65477
G1 X134.718 Y168.744 E.01727
G1 X168.744 Y134.718 E1.6792
G1 X168.744 Y134.224 E.01724
G1 X134.224 Y168.744 E1.70358
G1 X133.729 Y168.744 E.01727
G1 X168.744 Y133.729 E1.728
G1 X168.744 Y133.235 E.01724
G1 X133.235 Y168.744 E1.75238
G1 X132.74 Y168.744 E.01727
G1 X168.744 Y132.74 E1.77681
G1 X168.744 Y132.245 E.01727
G1 X132.245 Y168.744 E1.80124
G1 X131.751 Y168.744 E.01724
G1 X168.744 Y131.751 E1.82562
G1 X168.744 Y131.256 E.01727
G1 X131.256 Y168.744 E1.85005
G1 X131.256 Y168.249 E.01727
G1 X168.249 Y131.256 E1.82562
G1 X167.755 Y131.256 E.01724
G1 X131.256 Y167.755 E1.80124
G1 X131.256 Y167.26 E.01727
G1 X167.26 Y131.256 E1.77681
G1 X166.766 Y131.256 E.01724
G1 X131.256 Y166.766 E1.75243
G1 X131.256 Y166.271 E.01727
G1 X166.271 Y131.256 E1.728
G1 X165.776 Y131.256 E.01727
G1 X131.256 Y165.776 E1.70358
G1 X131.256 Y165.282 E.01724
G1 X165.282 Y131.256 E1.6792
G1 X164.787 Y131.256 E.01727
G1 X131.256 Y164.787 E1.65477
G1 X131.256 Y164.293 E.01724
G1 X164.293 Y131.256 E1.63039
G1 X163.798 Y131.256 E.01727
G1 X131.256 Y163.798 E1.60596
G1 X131.256 Y163.303 E.01727
G1 X163.303 Y131.256 E1.58153
G1 X162.809 Y131.256 E.01724
G1 X131.256 Y162.809 E1.55715
G1 X131.256 Y162.314 E.01727
G1 X162.314 Y131.256 E1.53272
G1 X161.82 Y131.256 E.01724
G1 X131.256 Y161.82 E1.50835
G1 X131.256 Y161.325 E.01727
G1 X161.325 Y131.256 E1.48392
G1 X160.83 Y131.256 E.01727
G1 X131.256 Y160.83 E1.45949
G1 X131.256 Y160.336 E.01724
G1 X160.336 Y131.256 E1.43511
G1 X159.841 Y131.256 E.01727
G1 X131.256 Y159.841 E1.41068
G1 X131.256 Y159.347 E.01724
G1 X159.347 Y131.256 E1.3863
G1 X158.852 Y131.256 E.01727
G1 X131.256 Y158.852 E1.36187
G1 X131.256 Y158.357 E.01727
G1 X158.358 Y131.256 E1.33747
G1 X157.863 Y131.256 E.01727
G1 X131.256 Y157.863 E1.31307
G1 X131.256 Y157.368 E.01727
G1 X157.368 Y131.256 E1.28864
G1 X156.874 Y131.256 E.01724
G1 X131.256 Y156.874 E1.26426
G1 X131.256 Y156.379 E.01727
G1 X156.379 Y131.256 E1.23983
G1 X155.885 Y131.256 E.01724
G1 X131.256 Y155.885 E1.21545
G1 X131.256 Y155.39 E.01727
G1 X155.39 Y131.256 E1.19102
G1 X154.895 Y131.256 E.01727
G1 X131.256 Y154.895 E1.16659
G1 X131.256 Y154.401 E.01724
G1 X154.401 Y131.256 E1.14221
G1 X153.906 Y131.256 E.01727
G1 X131.256 Y153.906 E1.11779
G1 X131.256 Y153.412 E.01724
G1 X153.412 Y131.256 E1.09341
G1 X152.917 Y131.256 E.01727
G1 X131.256 Y152.917 E1.06898
G1 X131.256 Y152.422 E.01727
G1 X152.422 Y131.256 E1.04455
G1 X151.928 Y131.256 E.01724
G1 X131.256 Y151.928 E1.02017
G1 X131.256 Y151.433 E.01727
G1 X151.433 Y131.256 E.99574
G1 X150.939 Y131.256 E.01724
G1 X131.256 Y150.939 E.97136
G1 X131.256 Y150.444 E.01727
G1 X150.444 Y131.256 E.94694
G1 X149.949 Y131.256 E.01727
G1 X131.256 Y149.949 E.92251
G1 X131.256 Y149.455 E.01724
G1 X149.455 Y131.256 E.89813
G1 X148.96 Y131.256 E.01727
G1 X131.256 Y148.96 E.8737
G1 X131.256 Y148.466 E.01724
G1 X148.466 Y131.256 E.84932
G1 X147.971 Y131.256 E.01727
G1 X131.256 Y147.971 E.82489
G1 X131.256 Y147.477 E.01724
G1 X147.477 Y131.256 E.80051
G1 X146.982 Y131.256 E.01727
G1 X131.256 Y146.982 E.77608
G1 X131.256 Y146.487 E.01727
G1 X146.487 Y131.256 E.75166
G1 X145.993 Y131.256 E.01724
G1 X131.256 Y145.993 E.72728
G1 X131.256 Y145.498 E.01727
G1 X145.498 Y131.256 E.70285
G1 X145.004 Y131.256 E.01724
G1 X131.256 Y145.004 E.67847
G1 X131.256 Y144.509 E.01727
G1 X144.509 Y131.256 E.65404
G1 X144.014 Y131.256 E.01727
G1 X131.256 Y144.014 E.62961
G1 X131.256 Y143.52 E.01724
G1 X143.52 Y131.256 E.60523
G1 X143.025 Y131.256 E.01727
G1 X131.256 Y143.025 E.5808
G1 X131.256 Y142.531 E.01724
G1 X142.531 Y131.256 E.55643
G1 X142.036 Y131.256 E.01727
G1 X131.256 Y142.036 E.532
G1 X131.256 Y141.541 E.01727
G1 X141.541 Y131.256 E.50757
G1 X141.047 Y131.256 E.01724
G1 X131.256 Y141.047 E.48319
G1 X131.256 Y140.552 E.01727
G1 X140.552 Y131.256 E.45876
G1 X140.058 Y131.256 E.01724
G1 X131.256 Y140.058 E.43438
G1 X131.256 Y139.563 E.01727
G1 X139.563 Y131.256 E.40995
G1 X139.068 Y131.256 E.01727
G1 X131.256 Y139.068 E.38553
G1 X131.256 Y138.574 E.01724
G1 X138.574 Y131.256 E.36115
G1 X138.079 Y131.256 E.01727
G1 X131.256 Y138.079 E.33672
G1 X131.256 Y137.585 E.01724
G1 X137.585 Y131.256 E.31234
G1 X137.09 Y131.256 E.01727
G1 X131.256 Y137.09 E.28791
G1 X131.256 Y136.596 E.01724
G1 X136.596 Y131.256 E.26353
G1 X136.101 Y131.256 E.01727
G1 X131.256 Y136.101 E.2391
G1 X131.256 Y135.606 E.01727
G1 X135.606 Y131.256 E.21467
G1 X135.112 Y131.256 E.01724
G1 X131.256 Y135.112 E.1903
G1 X131.256 Y134.617 E.01727
G1 X134.617 Y131.256 E.16587
G1 X134.123 Y131.256 E.01724
G1 X131.256 Y134.123 E.14149
G1 X131.256 Y133.628 E.01727
G1 X133.628 Y131.256 E.11706
G1 X133.133 Y131.256 E.01727
G1 X131.256 Y133.133 E.09263
G1 X131.256 Y132.639 E.01724
G1 X132.639 Y131.256 E.06825
G1 X132.144 Y131.256 E.01727
G1 X131.256 Y132.144 E.04382
G1 X131.256 Y131.65 E.01724
G1 X131.806 Y131.099 E.02717
; stop printing object square.stl id:0 copy 0
;WIPE_START
G1 F7200;_WIPE
G1 X131.256 Y131.65 E-.1849
G1 X131.256 Y132.144 E-.11732
G1 X132.144 Y131.256 E-.29826
G1 X132.639 Y131.256 E-.11756
G1 X132.395 Y131.5 E-.08196
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G1 Z3.88 F600 ; Move print head up
G1 X5 Y250.75 F9000 ; present print
G1 Z71.88 F600 ; Move print head further up
G1 Z180 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors
; objects_info = {"objects":[{"name":"square.stl id:0 copy 0","polygon":[[170.000,170.000],[130.000,170.000],[130.000,130.000],[170.000,130.000]]}]}
; filament used [mm] = 413.43
; filament used [cm3] = 0.99
; filament used [g] = 1.23
; filament cost = 0.02
; total filament used [g] = 1.23
; total filament cost = 0.02
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 7m 24s
; estimated first layer printing time (normal mode) = 57s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 5x5,295x5,295x295,5x295
; bed_temperature = 60
; bed_temperature_extruder = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 250
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights = 
; compatible_printers_condition_cummulative = "printer_model=~/(ENDER|CR|SERMOON).*/ and nozzle_diameter[0]==0.4";printer_notes=~/.*PRINTER_VENDOR_CREALITY.*/
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 500
; default_filament_profile = "Generic PLA @CREALITY"
; default_print_profile = "0.16 mm OPTIMAL (0.4 mm nozzle) @CREALITY"
; deretract_speed = 30
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.1
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.85} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.42
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 55
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.44
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_abrasive = 0
; filament_colour = #DDDDDD
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = "Generic PLA @CREALITY"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filament_wipe = nil
; fill_angle = 45
; fill_density = 0%
; fill_pattern = grid
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_infill_speed = 0
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 30
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = octoprint
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = 150
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.44
; infill_first = 0
; infill_overlap = 23%
; infill_speed = 60
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 10%
; ironing_spacing = 0.1
; ironing_speed = 20
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 0.24
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 500
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.32
; max_print_height = 300
; max_print_speed = 100
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.06
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{print_time}_{digits(layer_height,1,2)}mm_{temperature[0]}C_{filament_type[0]}_{printer_model}.gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M25 ; pause print
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.44
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = 0.24 mm DRAFT SPEED (0.4 mm nozzle) @CREALITY
; printer_model = ENDER3S1PLUS
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_CREALITY\nPRINTER_MODEL_ENDER3S1PLUS\nPRINTER_HAS_ULTRADETAIL
; printer_settings_id = Creality Ender-3 S1 Plus (0.4 mm nozzle)
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; profile_vendor = Creality
; profile_version = 1.1.0
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0.2
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 30
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 3
; skirt_height = 2
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20
; small_perimeter_speed = 30
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.44
; solid_infill_speed = 60
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S{is_nil(idle_temperature[0]) ? 150 : idle_temperature[0]} ; set temporary nozzle temp to prevent oozing during homing\nM140 S{first_layer_bed_temperature[0]} ; set final bed temp\nG4 S30 ; allow partial nozzle warmup\nG28 ; home all axis and restore leveling\nG1 Z50 F240\nG1 X2.0 Y10 F3000\nM104 S{first_layer_temperature[0]} ; set final nozzle temp\nM190 S{first_layer_bed_temperature[0]} ; wait for bed temp to stabilize\nM109 S{first_layer_temperature[0]} ; wait for nozzle temp to stabilize\nG1 Z0.28 F240\nG92 E0\nG1 X2.0 Y140 E10 F1500 ; prime the nozzle\nG1 X2.3 Y140 F5000\nG92 E0\nG1 X2.3 Y10 E10 F1200 ; prime the nozzle\nG92 E0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.15
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.36
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 1
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 40
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 205
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 30
; top_solid_layers = 4
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
